### ISSUE TITLE
List of figures should only be printed if \totalfigures > 0

### ISSUE THREAD

**Issue by pddzaic** [axelsommerfeldt/caption#2] opened 2018-01-10 09:03 UTC
The following examples shows, the bug in the package _totalcount_:

```
\documentclass[]{article}
\RequirePackage[figure,table]{totalcount}

\begin{document}
\iftotaltables
   \listoftables
\fi

\iftotalfigures
   \listoffigures
\fi

\setcounter{figure}{-1}
This report contains \totalfigures figures.

\end{document}
```

List of figures should only be printed if \totalfigures > 0

The same issue is valid for \listoftables

**Comment by u-fischer** [comment] 2018-01-10 09:52
I don't really see how negative numbers could appear in a sensible document, so it is imho not a bug if totalcount assumes that the numbers are all greater or equal to zero. But it is easy to change the test so that it handle negative values too:

```
\documentclass[]{article}
\usepackage[figure,table]{totalcount}
\makeatletter
\renewcommand*\totalcount@set[2]{%
  \@ifundefined{c@totalcount@#1}%
    {}%
    {\global\@namedef{total#1s}{#2\totalcount@xspace}%
     \ifnum#2>0\relax 
       \global\@nameuse{total#1strue}%
     \fi}}

\makeatother

\begin{document}
\iftotaltables
   \listoftables
\fi

\iftotalfigures
   \listoffigures
\fi

\setcounter{figure}{-1}
This report contains \totalfigures\ figures.

\end{document}
```

**Comment by pddzaic** [comment] 2018-01-10 12:43
Ulrike, I don't want to start the diskussion, if something is a bug or a feature. :-)

Generally I think, that the list of tables and figures should only be printed if the value of the counter \iftotalfigures is greater than 0. In this case we do not need any assumtions.

I don't understand the code presented by Ulrike, but it seems, that she knows what she did. :-) It would be nice if this could be taken into account for the next update of the package.

**Comment by axelsommerfeldt** [comment] 2018-01-21 10:50
I agree. It's a small change, makes the package more robust, and I don't see that it makes any harm. So I just merged the pull request https://github.com/axelsommerfeldt/caption/pull/3

Thanks for the contribution!

**Closed by axelsommerfeldt** 2018-01-21 10:50 UTC

**Comment by axelsommerfeldt** [comment] 2018-05-02 08:01
Backported to branch 3.3 with commit 7901c157f148b69b38478ea6fb540bb32ae90937 and prepared for CTAN release with commit a5a0e2b65478ed4fb8d1239cd933264479a1d0b2
